my:
  greeting: Hello Application Local GitHub
list:
  of:
    numbers: Application,One,Two,Three,Four,Five,Six,Seven

dbValues: "{connectionString:'spring-config', username:'server', password:'server'}"
app:
  name: Application Local Github
  description: Welcome to Application Local Github.com
