my:
  greeting: Hello Dev Properties
list:
  of:
    numbers: dev,One,Two,Three,Four,Five,Six,Seven

dbValues: "{connectionString:'spring-config', username:'server', password:'server'}"
app:
  name: dev Local Github
  description: Welcome to dev Local Github.com
