spring:
  port: 8087
my:
  greeting: Hello Spring-Boot-Config-Service Refresh
list:
  of:
    numbers: dev,One,Two,Three,Four,Five,Six,Eight,Nine

dbValues: "{connectionString:'spring-config', username:'server', password:'server'}"
app:
  name: Spring-Boot-Config-Service Local Github refresh
  description: v1 Newly Updated Welcome to Spring-Boot-Config-Service Local Github.com
